name: Stylelint Check

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  stylelint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Use the latest stable Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Stylelint
        run: npx stylelint "**/*.css"

