name: HTML Lint with Tidy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install tidy
        run: sudo apt-get install -y tidy

      - name: Run tidy on HTML files
        run: |
          find . -name "*.html" -exec tidy -errors {} \;

